application/config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #     resources :comments
  #     resources :posts
  #     resources :roles
  #     resources :users
  #
  #     root to: "comments#index"
  #   end

  namespace :admin do
    resources :users
    resources :roles, only: [:index, :show]
    root to: "users#index"
  end

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  resources :posts do
    resources :comments
    member do
      get 'download_pdf'
    end
  end

  root 'pages#home'

  resources :pages do
    collection do
      get 'home'
      get 'find'
      get 'privacy'
    end
  end

end

application/app/models/post.rb
# Model Post reprezentuje posty tworzone przez użytkowników.
#
# @!attribute [rw] user_id
#   @return [Integer] ID użytkownika, który stworzył post
# @!attribute [rw] title
#   @return [String] tytuł posta
# @!attribute [rw] content
#   @return [String] treść posta
class Post < ApplicationRecord
  # Relacja z modelem User
  # @return [User]
  belongs_to :user

  # Relacja z modelem Comment, z zależnością usuwania powiązanych komentarzy
  # @return [ActiveRecord::Associations::CollectionProxy<Comment>]
  has_many :comments, dependent: :destroy

  # Walidacja obecności user_id
  # @return [void]
  validates :user_id, presence: true

  # Walidacja obecności tytułu
  # @return [void]
  validates :title, presence: true

  # Walidacja obecności treści
  # @return [void]
  validates :content, presence: true

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: {
    number_of_shards: 1,
    number_of_replicas: 0,
    analysis: {
      filter: {
        lowercase_filter: {
          type: "lowercase"
        }
      },
      analyzer: {
        lowercase_analyzer: {
          type: "custom",
          tokenizer: "standard",
          filter: ["lowercase_filter"]
        }
      }
    }
  } do
    mappings dynamic: 'false' do
      indexes :title, type: :text, analyzer: 'lowercase_analyzer'
      indexes :content, type: :text, analyzer: 'lowercase_analyzer'
    end
  end

  # Przygotowuje JSON do zindeksowania w Elasticsearch
  #
  # @param options [Hash] opcje indeksowania
  # @return [Hash] zindeksowane dane w formacie JSON
  def as_indexed_json(options = {})
    json = as_json(only: [:title, :content, :user_id])
    json.merge!(
      'title' => json['title'].downcase,
      'content' => json['content'].downcase
    )
    json
  end

end

application/app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

application/app/controllers/posts_controller.rb
# Kontroler PostsController obsługuje operacje związane z postami.
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :download_pdf, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:edit, :update, :destroy, :download_pdf]

  # Wyświetla listę wszystkich postów z paginacją.
  #
  # @return [void]
  def list
    @posts = Post.page(params[:page]).per(10)
  end

  # Wyświetla listę wszystkich postów z paginacją w formacie JSON.
  #
  # @return [void]
  def index
    @posts = Post.page(params[:page]).per(10)
    render json: {
      posts: @posts,
      current_page: @posts.current_page,
      total_pages: @posts.total_pages,
      total_count: @posts.total_count
    }
  end

  # Wyświetla pojedynczy post i jego komentarze z paginacją.
  #
  # @return [void]
  def show
    @comments = @post.comments.page(params[:page]).per(10)
    # render json: { post: @post, comments: @comments }
  end

  # def download_pdf
  #   @post = Post.find(params[:id])
  #   @comments = @post.comments
  #
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #       pdf = generate_pdf(@post, @comments)
  #
  #       send_data pdf.render, filename: "post.pdf", type: "application/pdf", disposition: "attachment"
  #     end
  #   end
  # end

  #require 'nokogiri'

  # def download_pdf
  #   @post = Post.find(params[:id])
  #   @comments = @post.comments
  #
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #
  #       doc = Nokogiri::HTML::DocumentFragment.parse('')
  #
  #       head_content = <<-HTML
  #         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  #         <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  #         <style>
  #           body { font-family: 'Roboto', sans-serif; }
  #         </style>
  #       HTML
  #
  #       doc << head_content
  #
  #       doc << "<h1>Title: #{@post.title}</h1>"
  #       doc << "<p>Content: #{@post.content}</p>"
  #       doc << "<p>#{@post.created_at} </p>"
  #
  #       # Append comments if any
  #       if @comments.any?
  #         doc << "<div class='comments'>"
  #         @comments.each do |comment|
  #           doc << "<div class='comment'>"
  #           if comment.user
  #             doc << "<p>User: #{comment.user.email}</p>"
  #           else
  #             doc << "<p>User: Gość</p>"
  #           end
  #           doc << "<p>Content: #{comment.content}</p>"
  #           doc << "<p>Updated At: #{comment.updated_at&.strftime('%d %b %Y %H:%M:%S')}</p>"
  #           doc << "</div>"
  #         end
  #         doc << "</div>"
  #       else
  #         doc << "<p>No comments.</p>"
  #       end
  #
  #       html = doc.to_html
  #
  #       file_name = "#{@post.title}-#{Time.now.strftime('%Y%m%d%H%M%S')}.pdf"
  #
  #       save_path = Rails.root.join("public/export", file_name)
  #
  #       PdfsGenerateJob.perform_now(html, save_path.to_s, @post.id)  # Use perform_now for immediate processing
  #
  #       send_file save_path, type: 'application/pdf', disposition: 'attachment', filename: file_name
  #     end
  #   end
  # end

  # def download_pdf
  #   Rails.logger.info "****************************************"
  #   Rails.logger.info "Entering download_pdf method"
  #   @post = Post.find(params[:id])
  #   @comments = @post.comments
  #
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #
  #       html = render_to_string(template: 'app/views/posts/show.pdf.erb', formats: [:html], locals: { post: @post, comments: @comments }, layout: 'app/views/layouts/pdf.html')
  #
  #       file_name = "#{@post.title}-#{Time.now.strftime('%Y%m%d%H%M%S')}.pdf"
  #
  #       save_path = Rails.root.join("public/export", file_name)
  #
  #       PdfsGenerateJob.perform_now(html, save_path.to_s, @post.id)  # Use perform_now for immediate processing
  #
  #       send_file save_path, type: 'application/pdf', disposition: 'attachment', filename: file_name
  #     end
  #   end
  # end


  # Generuje plik PDF dla danego posta i jego komentarzy.
  #
  # @return [void]
  def download_pdf
    @post = Post.find(params[:id])
    @comments = @post.comments

    respond_to do |format|
      format.pdf do

        pdf_content = render_to_string(
          pdf: "#{@post.title}-#{Time.now.strftime('%Y%m%d%H%M%S')}",
          template: 'posts/show',
          layout: 'pdf',
          locals: { post: @post, comments: @comments },
          lang: "pl",
          encoding: 'UTF-8'
        )

        file_name = "#{@post.title}-#{Time.now.strftime('%Y%m%d%H%M%S')}.pdf"

        save_path = Rails.root.join("public/export", file_name)

        File.open(save_path, 'wb') do |file|
          file << pdf_content
        end

        send_file save_path, type: 'application/pdf', disposition: 'attachment', filename: file_name
      end
    end
  end

  # Inicjalizuje nowy post.
  #
  # @return [void]
  def new
    @post = Post.new
  end

  # Tworzy nowy post.
  #
  # @return [void]
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post został pomyślnie utworzony.'
    else
      render :new
    end
  end

  # Edytuje istniejący post.
  #
  # @return [void]
  def edit
    @post = Post.find(params[:id])
  end

  # Aktualizuje istniejący post.
  #
  # @return [void]
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'Post został pomyślnie zaktualizowany.'
    else
      flash.now[:alert] = 'Nie udało się zaktualizować posta.'
      redirect_to @post
    end
  end


  # Usuwa istniejący post.
  #
  # @return [void]
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url, notice: 'Post został pomyślnie usunięty.'
  end

  private

  # Silne parametry dla posta.
  #
  # @return [ActionController::Parameters] dozwolone parametry
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  # Ustawia post na podstawie ID z parametrów.
  #
  # @return [void]
  def set_post
    @post = Post.find(params[:id])
  end

  # Uwierzytelnia, czy aktualny użytkownik jest administratorem.
  #
  # @return [void]
  def authorize_admin
    unless current_user&.admin?
      redirect_to @post, alert: 'Nie masz uprawnień do wykonania tej akcji.'
    end
  end

  # def generate_pdf(post, comments)
  #   preprocessed_post_content = replace_polish_characters(post.content)
  #
  #   Prawn::Document.new do |pdf|
  #     pdf.text "Post: #{post.title}"
  #     pdf.text "Content: #{preprocessed_post_content}"
  #
  #     if comments.any?
  #       pdf.move_down 10
  #       pdf.text "Comments:"
  #       comments.each do |comment|
  #         preprocessed_comment_content = replace_polish_characters(comment.content)
  #
  #         pdf.text "User: #{comment.user.email if comment.user}"
  #         pdf.text "Content: #{preprocessed_comment_content}"
  #         pdf.text "Updated At: #{comment.updated_at&.strftime('%d %b %Y %H:%M:%S')}"
  #         pdf.move_down 10
  #       end
  #     else
  #       pdf.text "No comments."
  #     end
  #   end
  # end

  # def replace_polish_characters(text)
  #   polish_chars_mapping = {
  #     'ą' => 'a',
  #     'ć' => 'c',
  #     'ę' => 'e',
  #     'ł' => 'l',
  #     'ń' => 'n',
  #     'ó' => 'o',
  #     'ś' => 's',
  #     'ź' => 'z',
  #     'ż' => 'z'
  #   }
  #
  #   text.tr(polish_chars_mapping.keys.join, polish_chars_mapping.values.join)
  # end

end

application/app/helpers/posts_helper.rb
module PostsHelper
end

application/app/views/posts/download_pdf.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.user.email if @post.user %></p>
<p><%= @post.content %></p>
<p>Ostatnia data modyfikacji: <%= @post.updated_at.strftime("%d %b %Y %H:%M:%S") %></p>

<% if @comments.any? %>
  <div class="comments">
    <% @comments.each do |comment| %>
      <div class="comment">
        <% if comment.user %>
          <p><%= comment.user.email %></p>
        <% else %>
          <p>Gość</p>
        <% end %>
        <p><%= comment.content %></p>
        <p><%= comment.updated_at&.strftime("%d %b %Y %H:%M:%S") %></p>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Brak komentarzy.</p>
<% end %>

<p>Download</p>

application/app/views/posts/new.html.erb
<head>
  <title>Dodaj Post</title>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Strona Główna", home_pages_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Dodaj nowy post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Znajdź Post", find_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Polityka Prywatności", privacy_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link">Cześć <%= current_user.email %></span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="nav-link">Nie jesteś zalogowany</span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 text-center">
      <h1>Dodaj Post</h1>
    </div>
  </div>


    <div class="row justify-content-center">
      <div class="col-lg-6">
        <%= form_with(model: @post, method: :post, class: "my-form") do |form| %>
          <div class="form-group">
            <%= form.label 'Tytuł' %>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label 'Treść' %>
            <%= form.text_area :content, class: "form-control" %>
          </div>

          <%= form.submit "Utwórz post", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

application/app/views/posts/show.html.erb
<head>
  <title>Post</title>
  <%#= javascript_include_tag 'controllers/edit_post' %>
  <%#= javascript_include_tag 'controllers/edit_comment' %>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Strona Główna", home_pages_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Dodaj nowy post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Znajdź Post", find_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Polityka Prywatności", privacy_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link">Cześć <%= current_user.email %></span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="nav-link">Nie jesteś zalogowany</span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="rounded border p-4 bg-light">
        <h1><%= @post.title %></h1>
        <p><%= @post.user.email if @post.user %></p>
        <p><%= @post.content %></p>
        <p>Ostatnia data modyfikacji: <%= @post.updated_at.strftime("%d %b %Y %H:%M:%S") %></p>
        <% if current_user&.admin? %>
          <button class="btn btn-secondary edit-post-btn" data-post-id="<%= @post.id %>">Edytuj post</button>
          <%= link_to 'Pobierz PDF', download_pdf_post_path(@post, format: :pdf), class: 'btn btn-secondary', target: '_blank' %>
      <% end %>
      </div>

      <div id="post-edit-form-<%= @post.id %>" class="post-edit-form rounded border p-4 bg-light mb-4" style="display: none;">
        <%= form_with(model: @post, local: true) do |form| %>
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :content %>
            <%= form.text_area :content, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.submit 'Edytuj', class: "btn btn-primary" %>
            <button type="button" class="btn btn-secondary cancel-edit-post-btn" data-post-id="<%= @post.id %>">Porzuć</button>
          </div>
        <% end %>
      </div>
      <% if @comments.any? %>
        <div class="comment-section rounded border p-4 bg-light mb-4" style="max-height: 400px; overflow-y: auto;">
          <% @comments.each do |comment| %>
            <div class="comment rounded border p-4 bg-light mb-4">
              <% if comment.user %>
                <p><%= comment.user.email %></p>
              <% else %>
                <p>Gość</p>
              <% end %>

              <p><%= comment.content %></p>
              <p><%= comment.updated_at&.strftime("%d %b %Y %H:%M:%S") %></p>
              <% if current_user&.admin? %>
                <button class="btn btn-secondary edit-comment-btn" data-comment-id="<%= comment.id %>">Edytuj komentarz</button>

                <%= form_with(model: [@post, comment], method: :delete, local: true) do %>
                  <%= submit_tag 'Usuń komentarz', class: "btn btn-danger" %>
                <% end %>
              <% end %>
            </div>

            <div id="comment-edit-form-<%= comment.id %>" class="comment-edit-form rounded border p-4 bg-light mb-4" style="display: none;">
              <%= form_with(model: [@post, comment], local: true) do |form| %>
                <div class="form-group">
                  <%= form.label :content %>
                  <%= form.text_area :content, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= form.submit 'Edytuj', class: "btn btn-primary" %>
                  <button type="button" class="btn btn-secondary cancel-edit-comment-btn" data-comment-id="<%= comment.id %>">Porzuć</button>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= paginate @comments %>
        </div>
      <% else %>
        <p class="rounded border p-4 bg-light">Brak komentarzy.</p>
      <% end %>
    </div>
  </div>
</div>


<%= render 'comments/form' %>


<script>
    document.addEventListener('turbo:load', function() {
        console.log("script loaded");
        document.querySelectorAll('.edit-post-btn').forEach(button => {
            button.addEventListener('click', function() {
                const postId = this.dataset.postId;
                document.getElementById(`post-edit-form-${postId}`).style.display = 'block';
            });
        });

        document.querySelectorAll('.cancel-edit-post-btn').forEach(button => {
            button.addEventListener('click', function() {
                const postId = this.dataset.postId;
                document.getElementById(`post-edit-form-${postId}`).style.display = 'none';
            });
        });

        // Pokaż formularz edycji komentarza
        document.querySelectorAll(".edit-comment-btn").forEach(button => {
            button.addEventListener("click", function() {
                const commentId = this.dataset.commentId;
                document.getElementById(`comment-edit-form-${commentId}`).style.display = 'block';
            });
        });

        // Ukryj formularz edycji komentarza, gdy kliknięty przycisk "Porzuć"
        document.querySelectorAll(".cancel-edit-comment-btn").forEach(button => {
            button.addEventListener("click", function() {
                const commentId = this.dataset.commentId;
                document.getElementById(`comment-edit-form-${commentId}`).style.display = 'none';
            });
        });
    });
</script>

application/app/views/posts/show.pdf.erb
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post</title>
  <style>
      .post, .comment {
          border: 1px solid #ccc;
          margin: 20px auto;
          padding: 15px;
          text-align: center;
          width: 80%;
          box-shadow: 2px 2px 12px rgba(0, 0, 0, 0.1);
      }

      .comments {
          margin-top: 30px;
      }

      .comment {
          margin-bottom: 15px;
      }

      body {
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;
          font-family: Arial, sans-serif;
          background-color: #f4f4f4;
      }
  </style>
</head>
<body>
<div class="post">
  <h1><%= @post.title %></h1>
  <p><%= @post.user.email if @post.user %></p>
  <p><%= @post.content %></p>
  <p>Ostatnia data modyfikacji: <%= @post.updated_at.strftime("%d %b %Y %H:%M:%S") %></p>
</div>

<% if @comments.any? %>
  <div class="comments">
    <% @comments.each do |comment| %>
      <div class="comment">
        <% if comment.user %>
          <p><%= comment.user.email %></p>
        <% else %>
          <p>Gość</p>
        <% end %>
        <p><%= comment.content %></p>
        <p><%= comment.updated_at&.strftime("%d %b %Y %H:%M:%S") %></p>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Brak komentarzy.</p>
<% end %>
</body>
</html>