application/config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #     resources :comments
  #     resources :posts
  #     resources :roles
  #     resources :users
  #
  #     root to: "comments#index"
  #   end

  namespace :admin do
    resources :users
    resources :roles, only: [:index, :show]
    root to: "users#index"
  end

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  resources :posts do
    resources :comments
    member do
      get 'download_pdf'
    end
  end

  root 'pages#home'

  resources :pages do
    collection do
      get 'home'
      get 'find'
      get 'privacy'
    end
  end

end

application/app/views/pages/find.html.erb
<head>
  <title>Znajdź Post</title>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Strona Główna", home_pages_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Dodaj nowy post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Znajdź Post", find_pages_path, class: "nav-link active" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Polityka Prywatności", privacy_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link">Cześć <%= current_user.email %></span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="nav-link">Nie jesteś zalogowany</span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="rounded border p-4 bg-light mb-4">
        <h1>Znajdź Post</h1>
        <%= form_with(url: find_pages_path, method: :get, local: true, class: "my-form") do |form| %>
          <div class="input-group mb-3">
            <%= form.text_field :title, class: "form-control", placeholder: "Podaj tytuł postu" %>
            <div class="input-group-append">
              <%= form.submit "Wyszukaj", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>

      <% if @posts.any? %>
        <% @posts.each do |post| %>
          <div class="rounded border p-4 bg-light mb-4">
            <%= link_to post.title, post_path(post), class: "post-link" %>
            <p><%= post.content %></p>
            <p><%= post.created_at&.strftime("%d %b %Y %H:%M:%S") %></p>
            <!-- Add any other post details you want to display -->
            <% if current_user&.admin? %>
              <%= form_with(model: post, method: :delete, local: true) do %>
                <%= submit_tag 'Usuń post', class: "btn btn-danger" %>
              <% end %>
            <% end %>
          </div>
        <% end %>

        <%= paginate @posts %>
      <% else %>
        <p class="rounded border p-4 bg-light">Nie znaleziono żadnego postu.</p>
      <% end %>
    </div>
  </div>
</div>

application/app/views/pages/home.html.erb
<head>
  <title>Strona Główna</title>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Strona Główna", home_pages_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Dodaj nowy post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Znajdź Post", find_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Polityka Prywatności", privacy_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link">Cześć <%= current_user.email %></span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="nav-link">Nie jesteś zalogowany</span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 text-center">
      <h1>Strona Główna</h1>
    </div>
  </div>
</div>

<% if current_user %>
  <p>Cześć <%= current_user.email %></p><br>
  <p>Twoje role: <%= current_user.roles.map(&:name).join(", ") %></p><br>
  <% if current_user.has_role?(:admin) %>
    <p>Liczba wszystkich użytkowników: <%= User.count %></p>
  <% end %>
<% else %>
  <p>Nie jesteś zalogowany.</p><br>
  <p>Możesz zamieszczać tylko komentarze.</p>
<% end %>

application/app/views/pages/privacy.html.erb
<head>
  <title>Prywatność</title>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Strona Główna", home_pages_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Dodaj nowy post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Znajdź Post", find_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Polityka Prywatności", privacy_pages_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link">Cześć <%= current_user.email %></span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="nav-link">Nie jesteś zalogowany</span>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-3">
            <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 text-center">
      <h1>Polityka Prywatności</h1>
    </div>
  </div>
</div>